# chatbot-service/docker-compose.yml
version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RETAIL_APP_ENV=production
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - redis_data:/data

volumes:
  redis_data: